### ISSUE TITLE
Scroll bar does not appear in Chrome

### ISSUE THREAD

**Issue by V3ct0r** [soyjavi/tuktuk#10]
Si necesita algo mas por favor avísame, gracias.
If you need anything else please let me know, thanks.

![Error Tuktuk 1](https://f.cloud.github.com/assets/1517119/373215/a61ec8fc-a37a-11e2-8842-4ede0b294a3b.jpg)

**Comment by soyjavi** [comment]
Scrollbar in tuktuk is hidden via CSS

**Comment by V3ct0r** [comment]
Gracias por su tiempo, pero como puedo volver a la barra de desplazamiento?
Thanks for your time, but since I can show again the scroll bar?

**Comment by soyjavi** [comment]
CSS my friend!!! CSS
