### ISSUE TITLE
In "app" example user image exceeds its container.

### ISSUE THREAD

**Issue by buguibu** [soyjavi/tuktuk#12]
At least in Chrome on Win7, that image is displayed enormous.

I have fixed it removing class "vertical", jope it helps.

**Comment by soyjavi** [comment]
Can you send me a capture... I've Win7 environment :)

**Comment by buguibu** [comment]
![tuktuk app bug](https://f.cloud.github.com/assets/2544273/481712/e8b484ea-b86f-11e2-96be-b3871053ce2b.png)

Now the same problem occurs in Firefox 17 but not in Chrome.

I have try by myself modifing this:
1. img.responsive.vertical{ width: 100%
2. [data-tuktuk="boxes"] > aside.absolute:not(.right) { tranform: translateX(-150%)

But ... i have no real idea of what i'm doing.

**Comment by soyjavi** [comment]
I'm working in TukTuk 0.7.1 (with firefox support for flexbox)

**Comment by soyjavi** [comment]
Fixed (0.7.3)
