### ISSUE TITLE
Unreadable fonts in Chrome/Windows

### ISSUE THREAD

**Issue by JoseTomasTocino** [soyjavi/tuktuk#14]
Using Chrome latest on Windows 7/64, the texts are almost unreadable

![TukTuk - Blog Template](https://f.cloud.github.com/assets/648833/413635/7aa58332-abf9-11e2-8924-3b9d65fc5d74.png)

**Comment by soyjavi** [comment]
@font-family

**Comment by soyjavi** [comment]
Fixed (0.7.3)
