### ISSUE TITLE
Browser compatibility + documentation + examples

### ISSUE THREAD

**Issue by tarciozemel** [soyjavi/tuktuk#17]
Hi, guys! **Great** project you are mading, here, congrats!

In the the site, we can read "Don't try to use Tuktuk in your hated IE6", right? But I can't find some type of "compatibility table" to know in which browser I can use Tuktuk at all (or if it's consistent in the browsers with support).

I also tried to find some documentation in the site, but without success. Do you guys intend do put that in a near future? As I said, I **really** appreciated Tuktuk and, with some more infos and documentation and examples, I could contribute with the divulgation of Tuktuk translating the web site to brazilian portuguese and trying to spread the project from here. :-)

**Comment by soyjavi** [comment]
Hi! 

If you look a little you will see that the website itself serves as documentation, we believe this is the best way to see all that you can do with tuktuk.

I do not intend to compete with Bootstrap, and basically my goal is different (I'm focusing more on flexbox). Anyway if you want to see what you can really do with tuktuk, I invite you to take a look at

http://slid.us

**Comment by tarciozemel** [comment]
http://slid.us it's very pro, I'm more impressed about Tuktuk!

But some infos aren't possible to know without see/study all the code (e.g., the browsers compatibility info), wherefore I entered in the documentation subject and I think if this kind of information is present, the project will have a lot more adepts!  :-)

I'm serious think in make some tests with Tuktuk and, depending on results, adopt as my oficial rwd framework - and, obviously, talk a lot about it to my brazilian webdev pals (that is the reason I ask about documentation)!
