### ISSUE TITLE
Modal window doesn't open in Safari

### ISSUE THREAD

**Issue by james2doyle** [soyjavi/tuktuk#19]
Tried to debug this but I am lost as to what is going on. It just doesn't seem to want to show. The `active` class gets added but it still seems to be hiding somewhere on the page.

**Comment by soyjavi** [comment]
Modal Window works correctly on Safari… show me your code and I could help you :)

regards

**Comment by james2doyle** [comment]
I tried it on the latest github version and the [tuktuk](tuktuk.tapquo.com) site.

Safari 6.0.4

**Comment by lngsx** [comment]
For me Safari works very well but doesn't work in Chrome. It takes more than 10 seconds to show a modal after i clicked on a button. I also tried `TukTuk.Modal.show("modal");` but it come up with the same result.

**Comment by soyjavi** [comment]
Fixed (0.7.3)
