### ISSUE TITLE
Requesting a howto to build with grunt.

### ISSUE THREAD

**Issue by aabril** [soyjavi/tuktuk#21]
Hi.

I'm trying to generate the css code from the basic tuktuk package,
as far as I know I should use the gruntfile.coffee.

With the premises I have nodejs and grunt / grunt-cli installed, 
I use the 'grunt' command on the root of the project, but I have this error message.

```
albert@griset:~/dev/tuktuk$ grunt
grunt-cli: The grunt command line interface. (v0.1.6)

Fatal error: Unable to find local grunt.

If you're seeing this message, either a Gruntfile wasn't found or grunt
hasn't been installed locally to your project. For more information about
installing and configuring grunt, please see the Getting Started guide:

http://gruntjs.com/getting-started
```

It could be possible to attach some build instructions in the ReadMe file for newbies as me?

So much thanks in advance.

**Comment by soyjavi** [comment]
I'm sorry, but I think it's a problem with your GRUNT configuration.

regards,

**Comment by aabril** [comment]
Ok, I was considering to grunt as global (npm install -g grunt), and I need to install it as local.

This should be the steps:
1. npm install -g grunt-cli
2. npm init ---> _fill all details and it will create a package.json file._
3. npm install grunt (for grunt dependencies.)

Thanks anyway.

**Comment by aabril** [comment]
I'm feeling a few as a noob, but can't compile it succesfully. 

Gonna describe step by step the process followed:

My nodejs version:

<pre>
albert@griset:~/dev/tuktuk$ nvm ls
   v0.8.18     v0.8.23
current:    v0.8.23
default -> v0.8.23
</pre>    
1. _git clone_

<pre>
albert@griset:~/dev$ git clone https://github.com/soyjavi/tuktuk.git
Cloning into 'tuktuk'...
remote: Counting objects: 1236, done.
remote: Compressing objects: 100% (565/565), done.
remote: Total 1236 (delta 709), reused 1162 (delta 643)
Receiving objects: 100% (1236/1236), 1.15 MiB | 320 KiB/s, done.
Resolving deltas: 100% (709/709), done.
albert@griset:~/dev$ 
</pre>
1. _installing grunt and grunt-coffee on local path_

<pre>
albert@griset:~/dev$ cd tuktuk/
albert@griset:~/dev/tuktuk$ ls
LICENSE.md       gruntfile.coffee sources
README.md        site
albert@griset:~/dev/tuktuk$ npm install grunt grunt-coffee
npm http GET https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/grunt-coffee
npm http 304 https://registry.npmjs.org/grunt-coffee
npm http 304 https://registry.npmjs.org/grunt
npm http GET https://registry.npmjs.org/coffee-script
(etc etc etc)
grunt@0.4.1 node_modules/grunt
├── which@1.0.5
├── dateformat@1.0.2-1.2.3
├── colors@0.6.0-1
├── hooker@0.2.3
├── async@0.1.22
├── eventemitter2@0.4.11
├── underscore.string@2.2.0rc
├── coffee-script@1.3.3
├── iconv-lite@0.2.9
├── nopt@1.0.10 (abbrev@1.0.4)
├── rimraf@2.0.3 (graceful-fs@1.1.14)
├── minimatch@0.2.12 (sigmund@1.0.0, lru-cache@2.3.0)
├── lodash@0.9.2
├── findup-sync@0.1.2 (lodash@1.0.1)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.1)
└── js-yaml@2.0.5 (esprima@1.0.3, argparse@0.1.15)
grunt-coffee@0.0.6 node_modules/grunt-coffee
├── coffee-script@1.3.3
└── grunt@0.3.17 (dateformat@1.0.2-1.2.3, colors@0.6.0-1, semver@1.0.14, async@0.1.22, hooker@0.2.3, underscore@1.2.4, underscore.string@2.1.1, uglify-js@1.3.4, nopt@1.0.10, glob-whatev@0.1.8, temporary@0.0.5, gzip-js@0.3.2, jshint@0.9.1, connect@2.4.6, prompt@0.1.12, nodeunit@0.7.4)
albert@griset:~/dev/tuktuk$ 
</pre>
1. Trying to execute grunt (and failed)

<pre>
albert@griset:~/dev/tuktuk$ grunt
Loading "gruntfile.coffee" tasks...ERROR
>> Error: Unable to read "site/package/component.json" file (Error code: ENOENT).
Warning: Task "default" not found. Use --force to continue.
Aborted due to warnings.
albert@griset:~/dev/tuktuk$ 
</pre>

I guess I'm omitting some steps, but feel a little lost.

Thanks in advance.

**Comment by soyjavi** [comment]
I'm sorry, but I think it's your grunt / node config.

I asked to one of my colleagues in @tapquo to fork project and run grunt and it worked perfectly. I'm sorry, but I have to close this issue (because it isn't a issue).

**Comment by tolyo** [comment]
This is the line where the grunt buildfile is breaking down `pkg: grunt.file.readJSON "site/package/component.json"`. Is this file missing from the repo?

**Comment by aabril** [comment]
That was that for some reason I didn't update the git submodules. 
(maybe my fish shell, or an outdated git version, I need to figure out).

Easy fix:
- change directory to site/package 
- git submodule init
- git submodule update

And that's it.

**Comment by kmmbvnr** [comment]
I had same problem with another js project. Seems there is a bug somewere in js dev workflow tools, leads that not all grunt tasks are installed properly. And even if grunt deps installed globally it doesn't helps. You should install them locally.

I fixed that by manually installing everything listed in project package.json
