### ISSUE TITLE
Bower compatibility

### ISSUE THREAD

**Issue by ecentinela** [soyjavi/tuktuk#22]
Can you make your library (I mean the .styl files) available for bower?

Thank you.

**Comment by soyjavi** [comment]
Yes, I'm working on it :)

**Comment by soyjavi** [comment]
Bower it's for JS components, I think it's a bad idea use for other purpouse.

**Comment by ecentinela** [comment]
Bower is not for JS components. It's a package manager, no matter the asset type.
Bootstrap is a css project (mainly). It's on bower. Do you think it's a bad case?

**Comment by soyjavi** [comment]
TukTuk it's in Bower (because has JS library…) … but a source code of a part of project it's imposible in bower (I think).
