### ISSUE TITLE
Button on landing is not fully aligned with the input.

### ISSUE THREAD

**Issue by V3ct0r** [soyjavi/tuktuk#23]
In landing.html example, the button do not align with the input.
En ejemplo landing.html, el boton no aparece alineado con el input.

```
    <div class="row">
        <div class="column_6 offset_3 form subscribe">
            <input type="email" id="mail" class="large" placeholder="Your email address">
            <button class="button large icon envelope"></button>
        </div>
    </div>
```

Ese comportamiento es normal? o se trata de un error? gracias
That behavior is normal? or is it a mistake? thanks
![captura de pantalla de 2013-06-07 16 29 39](https://f.cloud.github.com/assets/1517119/626115/3dd0b7c6-cfb5-11e2-8f46-57ee50daccff.png)

**Comment by ranadeep47** [comment]
Maybe its the expected behaviour

**Comment by mrzafod** [comment]
@V3ct0r , its all because of iconfont. All icons are from FontAwesome package, so the line height of any glypth isnt the same as your base font (its defined in `em`s). Its a common issue for a most of front-end frameworks. You can define a font size or line height in `px` according to `1 em of glypth ~ 0.894 em of base font`

**Comment by V3ct0r** [comment]
Muchas gracias por su ayuda, yo pienso que con eso queda resuelto :)
Thank you very much for your help, I think that this is resolved :)
![captura de pantalla de 2013-06-10 17 07 34](https://f.cloud.github.com/assets/1517119/634290/0c86d52a-d216-11e2-86de-b6b672295bfe.png)

Solo me falta corregir cuando cambio el tamaño de la ventana que pasa esto
I just need to correct when I change the window size passes this
![captura de pantalla de 2013-06-11 11 15 45](https://f.cloud.github.com/assets/1517119/637862/0dc3b852-d2ae-11e2-95ff-2b4501c42bf4.png)

**Comment by soyjavi** [comment]
Pull request please :)
