### ISSUE TITLE
Package folder empty

### ISSUE THREAD

**Issue by fluxxus** [soyjavi/tuktuk#36]
When you download master zip file, the package folder is empty. I guess this is the place where all the stylesheets would need to be, so I guess that it shouldn't be empty:)

**Comment by roflzok** [comment]
Has been covered already so I guess reading resolved issues would be a good start. :)

https://github.com/soyjavi/tuktuk/pull/26

**Comment by fluxxus** [comment]
Thanks! I see that the questions aren't answered promptly, so maybe you can answer me this. The thing is that I haven't seen bigger mess of a CSS framework in my life. I am reffering to two files that are needed, namely tuktuk.css and theme.css file. 

No comments in the files, no separation of elements(forms, buttons. etc) from the grid and basic styles. I know that the creator is a renowned in the web industry and I really like the framework, from flat design to flex-box, but I can't understand why the two main files are such chaos?

**Comment by roflzok** [comment]
Hey man, sorry for the late reply. I'm not by a computer so I can't double check but are those two files compiled from what's included in the repo?

**Comment by soyjavi** [comment]
Package it's a gitsubmodule (for bower installs) 

https://github.com/soyjavi/package-tuktuk
