### ISSUE TITLE
questions about selector .row in tuktuk.grid.styl

### ISSUE THREAD

**Issue by alejo8591** [soyjavi/tuktuk#5]
located in the file /stylesheets/tuktuk.grid.styl this line 261 as follows:

``` css
.row
    margin: 0 auto
    width: 456px
    overflow: hidden

  .row .row
    margin: 0
    width: auto
    display: inline-block
```

Believe and if I'm not wrong should be :+1:  :

``` css
.row
    margin: 0 auto
    width: 456px
    overflow: hidden

    &.row
      margin: 0
      width: auto
      display: inline-block
```

**Comment by stereokai** [comment]
Not really, that would make an element with this class attribute: class="row row" which only applies the row class to that element and that's it
