### ISSUE TITLE
Get error on tuktuk.button.styl

### ISSUE THREAD

**Issue by ALTELMA** [soyjavi/tuktuk#51]
I try to compile css from folder styl, but error on tuktuk.button.styl with variable UNIT. I'm newbie on stylus and I don't know how to compile __init.style with tuktuk.button.styl.

Can advice me, please.

**Comment by V3ct0r** [comment]
You have install gulp?

**Comment by ALTELMA** [comment]
yes, I install all tools for compile stylus file. when I compile display an that error on tuktuk.button.styl

Advice me, please.

**Comment by V3ct0r** [comment]
En estos momentos acabo de descargar tuktuk de github y todo funciona correctamente. sigue estos pasos:

``` bash
git clone --recursive https://github.com/soyjavi/tuktuk.git
cd tuktuk
npm install  
gulp
```

Entra con esta url en tu navegar [http://localhost:8000](http://localhost:8000)

---

Right now I just downloaded tuktuk from github and everything works properly. follow these steps: 

``` bash
git clone --recursive https://github.com/soyjavi/tuktuk.git
cd tuktuk
npm install  
gulp
```

Enter this url into your browse [http://localhost:8000](http://localhost:8000)

**Comment by ALTELMA** [comment]
OK, It's work. Thanks you a lot for advice me.

**Comment by V3ct0r** [comment]
Me alegra ser de ayuda

---

Glad to be of help
