### ISSUE TITLE
Clearfix method

### ISSUE THREAD

**Issue by javierpose** [soyjavi/tuktuk#9]
The use of overflow: hidden as the clearfix method for a layout has many problems. For example, you can not use elements with position: absolute or negative margins because it will not display outside the bounds of the container (dropdown menus, tooltips,...). I think that the most up to date clearfix method is http://nicolasgallagher.com/micro-clearfix-hack/

**Comment by soyjavi** [comment]
I'll check !!! thanks :+1:

**Comment by javierpose** [comment]
You can see the problem in the descender of your fonts in your website. See attach image with a screenshot of your website
![overflow](https://f.cloud.github.com/assets/210588/176102/7da404c0-7b69-11e2-955d-60f71e06e001.PNG)

**Comment by stereokai** [comment]
I sincerely recommend using ![Normalize.css](https://github.com/necolas/normalize.css/), and ![this ](http://nicolasgallagher.com/about-normalize-css/) ![is ](http://stackoverflow.com/a/8357635/1049693) ![why](http://www.cssviking.com/normalize-not-reset-css).

We are using it on our webapp and it made things a lot easier on us with testing the UI on different browsers, desktop _and_ mobile.

**Comment by soyjavi** [comment]
I think it's solved

**Comment by javierpose** [comment]
Hi

You've just solved one of the effects of the problem. The problem is that this method clearfix is incorrect. The clearfix method overflow: hidden is sloppy, generates different problems and is only valid in controlled environments and not subject to changes. You can see another example of an effect generated by this method in the following image. In this example the tooltip is not seen complete, so users will have problems with any element with absolute position or negative margins.
![Captura de pantalla 2013-04-10 a las 22 52 12](https://f.cloud.github.com/assets/210588/364529/aa063252-a221-11e2-8ee2-e6b611e914fa.png)
